project:
  type: website
  output-dir: docs

website:
  title: "GameDev Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/raigneier
      - icon: twitter
        href: https://twitter.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - about.qmd
          - somepage.qmd
      - section: "Layout"
        contents:
          - about.qmd
          - somepage.qmd


  
format:
  html:
    theme: cosmo
    css: styles.css



