project:
  type: website
  output-dir: docs

website:
  title: "GameDev Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/raigneier
      - icon: twitter
        href: https://twitter.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "General"
        contents:
          - text: "Welcome"
            file: posts\news\00\index.qmd
          - text: "About author"
            file: about.qmd
      - section: "Arkanoid Series"
        contents:
          - text: "Introduction"
            file: posts\Arkanoid\01\index.qmd
          - text: "Setup and Tools"
            file: posts\Arkanoid\02\index.qmd
          - text: "Creating a project"
            file: posts\Arkanoid\03\index.qmd
          - text: "Input Handling"
            file: posts\Arkanoid\04\index.qmd
          - text: "Game Loop"
            file: posts\Arkanoid\05\index.qmd
  
format:
  html:
    theme: cosmo
    css: styles.css



